import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

test.afterAll(async ({ request }) => {
  await request.post("/api/system/test-shutdown").catch(() => undefined);
});

test("crop upload, model comparison, review, research and deletion", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Recognize vehicles across uploads." })).toBeVisible();
  await page.getByLabel("Site name", { exact: true }).fill("Crop test site");
  await page.getByRole("button", { name: "Create site", exact: true }).click();
  await expect(page.getByRole("heading", { name: "New crop experiment" })).toBeVisible();
  await expect(page.getByLabel("YOLO11 detector")).toHaveCount(0);
  await page.getByRole("button", { name: "Compare two images" }).click();
  await expect(page.getByRole("heading", { name: "Compare two vehicle images." })).toBeVisible();
  const firstPairImage = resolve("..", "..", "RTMDet-Tiny", "chosen crops", "vehicle_2", "t2_f00355.jpg");
  const secondPairImage = resolve("..", "..", "RTMDet-Tiny", "chosen crops", "vehicle_2", "t2_f00085.jpg");
  await page.getByLabel("Pair comparison name").fill("CoCa same truck");
  await page.getByLabel("First comparison image").setInputFiles(firstPairImage);
  await page.getByLabel("Second comparison image").setInputFiles(secondPairImage);
  await page.getByRole("button", { name: "Embed and compare" }).click();
  const pairResult = page.locator(".pair-result");
  await expect(pairResult.getByRole("heading", { name: "CoCa same truck" })).toBeVisible({ timeout: 30_000 });
  await expect(pairResult.getByText("Same vehicle", { exact: false })).toBeVisible();
  await expect(pairResult.getByText("Raw CoCa cosine", { exact: true })).toBeVisible();
  await expect(pairResult.getByText("STRUCTURED CRITERIA", { exact: false })).toBeVisible();
  await expect(pairResult.getByText("Criteria similarity", { exact: false })).toBeVisible();
  await expect(pairResult.getByAltText("First pair comparison image")).toBeVisible();
  await expect(pairResult.getByAltText("Second pair comparison image")).toBeVisible();
  await pairResult.getByText("CoCa semantic attributes", { exact: true }).first().click();
  await expect(pairResult.getByText("passenger car", { exact: true }).first()).toBeVisible();
  const pairDownloadStarted = page.waitForEvent("download");
  await pairResult.getByRole("link", { name: "Download vectors JSON" }).click();
  const pairDownload = await pairDownloadStarted;
  const pairJson = JSON.parse((await readFile((await pairDownload.path())!)).toString("utf8"));
  expect(pairJson.images[0].vectors.appearance).toHaveLength(2);
  expect(pairJson.images[0].vectors.color).toHaveLength(72);
  expect(pairJson.images[0].vectors.shape).toHaveLength(8100);
  expect(pairJson.images[0].vectors.semantic).toHaveLength(24);
  expect(pairJson.criteria_report.version).toBe("criteria-v1");
  expect(pairJson.criteria_report.plate_logo_type_viewpoint.model_text.image_1.label).toBe("unknown");
  await page.getByLabel("appearance comparison weight").fill("100");
  await page.getByLabel("color comparison weight").fill("0");
  await page.getByLabel("shape comparison weight").fill("0");
  await page.getByLabel("semantic comparison weight").fill("0");
  await page.getByLabel("Pair comparison threshold").fill("0.99");
  await page.getByRole("button", { name: "Apply scoring without re-embedding" }).click();
  await expect(pairResult.getByText("Different vehicles", { exact: false })).toBeVisible();
  await page.screenshot({ path: "test-results/reid-coca-pair-comparison.png", fullPage: true });
  await page.getByRole("button", { name: "Delete comparison CoCa same truck" }).click();
  await expect(page.getByRole("button", { name: "Delete comparison CoCa same truck" })).toHaveCount(0);
  await page.getByLabel("Pair encoder mode").selectOption("coca_visual");
  await page.getByLabel("Pair comparison name").fill("Visual only cosine");
  await page.getByLabel("First comparison image").setInputFiles(firstPairImage);
  await page.getByLabel("Second comparison image").setInputFiles(secondPairImage);
  await page.getByRole("button", { name: "Embed and compare" }).click();
  const visualResult = page.locator(".pair-result");
  await expect(visualResult.getByText("Raw CoCa visual cosine", { exact: true })).toBeVisible();
  await expect(visualResult.getByText("Standalone 512D visual tower only", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Delete comparison Visual only cosine" }).click();
  await page.getByLabel("Pair encoder mode").selectOption("coca_l14");
  await page.getByLabel("Pair comparison name").fill("CoCa L14 fusion");
  await page.getByLabel("First comparison image").setInputFiles(firstPairImage);
  await page.getByLabel("Second comparison image").setInputFiles(secondPairImage);
  await page.getByRole("button", { name: "Embed and compare" }).click();
  await expect(pairResult.getByText("Raw CoCa L/14 cosine", { exact: true })).toBeVisible();
  await pairResult.getByText("CoCa L/14 semantic attributes", { exact: true }).first().click();
  await expect(pairResult.getByText("passenger car", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Delete comparison CoCa L14 fusion" }).click();
  await page.getByLabel("Pair encoder mode").selectOption("coca_l14_visual");
  await page.getByLabel("Pair comparison name").fill("CoCa L14 visual cosine");
  await page.getByLabel("First comparison image").setInputFiles(firstPairImage);
  await page.getByLabel("Second comparison image").setInputFiles(secondPairImage);
  await page.getByRole("button", { name: "Embed and compare" }).click();
  await expect(visualResult.getByText("Raw CoCa L/14 visual cosine", { exact: true })).toBeVisible();
  await expect(visualResult.getByText("Standalone 768D visual tower only", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Delete comparison CoCa L14 visual cosine" }).click();
  await page.getByLabel("Pair encoder mode").selectOption("siglip2");
  await page.getByLabel("Pair comparison name").fill("SigLIP2 fusion");
  await page.getByLabel("First comparison image").setInputFiles(firstPairImage);
  await page.getByLabel("Second comparison image").setInputFiles(secondPairImage);
  await page.getByRole("button", { name: "Embed and compare" }).click();
  await expect(pairResult.getByText("Raw SigLIP2 cosine", { exact: true })).toBeVisible();
  await pairResult.getByText("SigLIP2 semantic attributes", { exact: true }).first().click();
  await expect(pairResult.getByText("passenger car", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Delete comparison SigLIP2 fusion" }).click();
  await page.getByLabel("Pair encoder mode").selectOption("siglip2_visual");
  await page.getByLabel("Pair comparison name").fill("SigLIP2 visual cosine");
  await page.getByLabel("First comparison image").setInputFiles(firstPairImage);
  await page.getByLabel("Second comparison image").setInputFiles(secondPairImage);
  await page.getByRole("button", { name: "Embed and compare" }).click();
  await expect(visualResult.getByText("Raw SigLIP2 visual cosine", { exact: true })).toBeVisible();
  await expect(visualResult.getByText("Standalone 768D visual tower only", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Delete comparison SigLIP2 visual cosine" }).click();
  await page.getByRole("button", { name: "Experiments", exact: true }).click();
  await page.getByLabel("Experiment name").fill("Crop comparison");
  // A 20x30 PNG also verifies that ingestion retains small crops.
  await page.getByLabel("Vehicle crops").setInputFiles({ name: "car.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAABQAAAAeCAIAAACjcKk8AAAAMElEQVR4nO3LIQIAIAwDsdL//3nY2gO5xueM3vnjqhkyDakZMg2pGTINqRkyDVqeL/veATtX+08NAAAAAElFTkSuQmCC", "base64") });
  await expect(page.getByRole("button", { name: "Upload & run experiment" })).toBeDisabled();
  await page.getByLabel("Vehicle class for car.png").selectOption("car");
  await page.getByRole("checkbox", { name: "OpenVINO vehicle-reid-0001", exact: true }).check();
  await page.getByRole("button", { name: "Upload & run experiment" }).click();
  await expect(page.getByRole("heading", { name: "Vehicle observations · 1" })).toBeVisible();
  await expect(page.getByAltText("Annotated vehicle result")).toBeVisible();
  const downloadStarted = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download all results (.zip)" }).click();
  const download = await downloadStarted;
  expect(download.suggestedFilename()).toBe("reid-Crop_comparison-results.zip");
  const archivePath = await download.path();
  expect(archivePath).not.toBeNull();
  const archive = await readFile(archivePath!);
  for (const member of ["manifest.json", "data/observations.csv", "data/cosine_comparisons.json", "images/queries/"]) {
    expect(archive.includes(Buffer.from(member))).toBeTruthy();
  }
  await page.getByRole("button", { name: "Confirm identity", exact: true }).click();
  await expect(page.getByText("Reviewed site identity", { exact: false })).toBeVisible();
  await page.getByText("Optional identity labels", { exact: true }).click();
  await page.getByLabel(/^True identity for /).fill("CAR_A");
  await page.getByRole("button", { name: "Save label", exact: true }).click();
  await page.screenshot({ path: "test-results/reid-crops.png", fullPage: true });

  await page.getByLabel("Experiment name").fill("Comparison query");
  await page.getByLabel("Vehicle crops").setInputFiles({ name: "query.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAABQAAAAeCAIAAACjcKk8AAAAMElEQVR4nO3LIQIAIAwDsdL//3nY2gO5xueM3vnjqhkyDakZMg2pGTINqRkyDVqeL/veATtX+08NAAAAAElFTkSuQmCC", "base64") });
  await page.getByLabel("Vehicle class for query.png").selectOption("car");
  await page.getByRole("button", { name: "Upload & run experiment" }).click();
  await expect(page.getByRole("heading", { name: "Comparison query" })).toBeVisible();
  await page.getByRole("button", { name: "View comparisons" }).click();
  const observationComparisons = page.locator(".comparison-inline");
  await expect(observationComparisons.getByRole("heading", { name: "Observation image comparisons" })).toBeVisible();
  await expect(observationComparisons.getByAltText("Query query.png")).toBeVisible();
  await expect(observationComparisons.getByAltText("Reference car.png")).toBeVisible();
  await expect(observationComparisons.getByText("Cosine #1", { exact: false })).toBeVisible();
  await expect(observationComparisons.getByText("Decision reference", { exact: true })).toBeVisible();
  await expect(observationComparisons.locator(".comparison-scores dd").filter({ hasText: /^VEHICLE_\d+$/ }).first()).toBeVisible();
  await page.getByRole("button", { name: "Open image comparison table" }).click();
  const experimentComparisons = page.locator(".comparison-experiment");
  await expect(experimentComparisons.getByRole("heading", { name: "Experiment image comparison table" })).toBeVisible();
  await experimentComparisons.getByLabel("Comparison encoder").selectOption("siglip");
  await expect(experimentComparisons.locator(".comparison-score-head strong").filter({ hasText: "SigLIP Base" })).toBeVisible();
  await experimentComparisons.getByLabel("Comparison decision role").selectOption("winning");
  await expect(experimentComparisons.getByText("1 comparisons", { exact: true })).toBeVisible();
  await expect(experimentComparisons.locator("a.comparison-image")).toHaveCount(2);
  await page.screenshot({ path: "test-results/reid-comparisons.png", fullPage: true });

  await page.getByRole("button", { name: "Accuracy & optional training" }).click();
  await page.getByLabel("Labeled truck folder").setInputFiles(resolve("..", "..", "RTMDet-Tiny", "chosen crops"));
  await expect(page.getByLabel("Benchmark preflight")).toContainText("46 images");
  await expect(page.getByLabel("Benchmark preflight")).toContainText("10 identities");
  await expect(page.getByText("vehicle_1 cannot be identification queries", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Run folder benchmark" }).click();
  await expect(page.getByRole("heading", { name: "chosen crops results" })).toBeVisible({ timeout: 30_000 });
  await expect(page.locator(".benchmark-summary tbody tr")).toHaveCount(11);
  await expect(page.getByText("11385 JPEG cards", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Prepare comparison images" }).click();
  const comparisonImagesLink = page.getByRole("link", { name: "Download model comparison images (.zip)" });
  await expect(comparisonImagesLink).toBeVisible({ timeout: 30_000 });
  const comparisonImagesDownloadStarted = page.waitForEvent("download");
  await comparisonImagesLink.click();
  const comparisonImagesDownload = await comparisonImagesDownloadStarted;
  const comparisonImagesArchive = await readFile((await comparisonImagesDownload.path())!);
  for (const member of ["manifest.json", "dinov2/comparisons.csv", "coca_l14/000001__same__fixture.jpg"]) {
    expect(comparisonImagesArchive.includes(Buffer.from(member))).toBeTruthy();
  }
  await page.getByRole("button", { name: "View compared images" }).click();
  const benchmarkComparisons = page.locator(".benchmark-comparison-browser");
  await expect(benchmarkComparisons.getByRole("heading", { name: "Benchmark image comparisons" })).toBeVisible();
  await expect(benchmarkComparisons.getByText("1035 pairs", { exact: true })).toBeVisible();
  await expect(benchmarkComparisons.locator(".benchmark-pair")).toHaveCount(24);
  await expect(benchmarkComparisons.getByAltText(/^First benchmark image /).first()).toBeVisible();
  await expect(benchmarkComparisons.getByAltText(/^Second benchmark image /).first()).toBeVisible();
  await expect(benchmarkComparisons.getByText("Cosine", { exact: false }).first()).toBeVisible();
  await benchmarkComparisons.getByLabel("Benchmark pair type").selectOption("same");
  await expect(benchmarkComparisons.getByText("Same truck", { exact: true }).first()).toBeVisible();
  await benchmarkComparisons.getByLabel("Benchmark comparison identity").selectOption("vehicle_2");
  await expect(benchmarkComparisons.locator(".benchmark-pair").first()).toBeVisible();
  await page.screenshot({ path: "test-results/reid-benchmark-comparisons.png", fullPage: true });
  await page.getByLabel("Results threshold").fill("1");
  const thresholdResponse = page.waitForResponse(response => response.url().includes("/threshold") && response.request().method() === "PUT");
  await page.getByRole("button", { name: "Apply without re-embedding" }).click();
  expect((await thresholdResponse).ok()).toBeTruthy();
  await expect(page.locator(".benchmark-summary tbody tr").first().locator("td").nth(1)).toHaveText("1.000");
  const benchmarkDownloadStarted = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download benchmark (.zip)" }).click();
  const benchmarkDownload = await benchmarkDownloadStarted;
  const benchmarkArchivePath = await benchmarkDownload.path();
  expect(benchmarkArchivePath).not.toBeNull();
  const benchmarkArchive = await readFile(benchmarkArchivePath!);
  for (const member of ["data/summary.csv", "data/pairwise_comparisons.json", "data/confusion_matrix.csv", "images/vehicle_1/"]) {
    expect(benchmarkArchive.includes(Buffer.from(member))).toBeTruthy();
  }
  await page.getByRole("button", { name: "Delete benchmark chosen crops" }).click();
  await page.getByLabel("Research encoder").selectOption("openvino");
  await expect(page.getByRole("button", { name: "Fine-tune locally · optional" })).toBeDisabled();
  await page.getByRole("checkbox", { name: "Crop comparison", exact: true }).check();
  await page.getByRole("button", { name: "Create labeled snapshot" }).click();
  await expect(page.getByRole("alert")).toContainText("six labeled identities");
  await page.getByRole("button", { name: "Experiments", exact: true }).click();
  await page.getByRole("button", { name: "Delete experiment Crop comparison", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button", { name: "Delete permanently", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Delete experiment Crop comparison", exact: true })).toHaveCount(0);
});
